//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product1
    {
        public int pId { get; set; }
        public string ptype { get; set; }
        public string pname { get; set; }
        public decimal pprice { get; set; }
        public int prating { get; set; }
        public string pdiscount { get; set; }
        public string pimage { get; set; }
        public string Description { get; set; }
    }
}
